spring:
  profiles:
    active: local
  jackson:
    time-zone: Asia/Seoul
    default-property-inclusion: non_null
  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  default-produces-media-type: application/json